version: '3.8'

services:
  ui_service:
    build:
      context: .
      dockerfile: services/ui_service/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - LLM_SERVICE_URL=http://llm_service:8002/generate
      - CHAT_SERVICE_URL=ws://chat_service:8000/ws
      - HISTORY_SERVICE_URL=http://history_service:8003
    volumes:
      - ./logs:/app/logs
    depends_on:
      - llm_service
      - chat_service
      - history_service

  llm_service:
    build:
      context: .
      dockerfile: services/llm_service/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./logs:/app/logs

  chat_service:
    build:
      context: .
      dockerfile: services/chat_service/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - LLM_SERVICE_URL=http://llm_service:8002/generate
    volumes:
      - ./logs:/app/logs

  history_service:
    build:
      context: .
      dockerfile: services/history_service/Dockerfile
    ports:
      - "8003:8003"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data

  # Logstash, Elasticsearch, and Kibana setup
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.15.0
    user: root 
    volumes:
      - ./services/common/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/app/logs:ro
    depends_on:
      - logstash
    command: ["filebeat", "-e", "-strict.perms=false"]  # Add this line to disable strict permission checks

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.0
    volumes:
      - ./services/common/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata: