FROM python:3.10-slim

WORKDIR /app

COPY requirements-common.txt .
COPY services/[service_name]/requirements.txt .
RUN pip install --no-cache-dir -r requirements-common.txt -r requirements.txt

COPY services/ui_service ./services/ui_service

EXPOSE 8501

CMD ["streamlit", "run", "services/ui_service/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
